// Generated by CoffeeScript 1.7.1
(function() {
  var Guides;

  module.exports = Guides = (function() {
    Guides.prototype.id = 1032;

    Guides.prototype.name = 'guides';

    function Guides(resource) {
      this.resource = resource;
      this.file = this.resource.file;
      this.data = [];
    }

    Guides.prototype.parse = function() {
      var direction, i, location, num_guides, _i, _results;
      this.file.seek(4, true);
      this.file.seek(8, true);
      num_guides = this.file.readInt();
      _results = [];
      for (i = _i = 1; 1 <= num_guides ? _i <= num_guides : _i >= num_guides; i = 1 <= num_guides ? ++_i : --_i) {
        location = (this.file.readInt() / 32).toFixed(1);
        direction = this.file.readByte() ? "horizontal" : "vertical";
        _results.push(this.data.push({
          location: location,
          direction: direction
        }));
      }
      return _results;
    };

    Guides.prototype["export"] = function() {
      return this.data;
    };

    return Guides;

  })();

}).call(this);
